### ISSUE TITLE
Data model for comics

### ISSUE THREAD

**Issue by dmevola** [dmevola/e-comics#2]
Includes:
    itemPublisher:  // ie. DC, Marvel, Etc
    itemTitle: //ie Batman, Wolverine, SuperMan vs Batman, etc.
    itemIssueTitle: //ie. The Night of the Bat
    itemIssueNumber //#124
    itemDescription: //Summary, etc
    itemCondition: //ie. (Poor, Fair, Good, Very Fine, Mint)
    itemPrice: //decimal
    itemImage: //string for link
    createdAt: //date defaulted
    username: //from user logged in when adding item
    reactions: [reactionSchema]

**Comment by ajureel** [comment]
May need to tweak mutations as we go
